spring:
  application:
    name: reserix-api

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always