spring:
  application:
    name: reserix-api

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: reserix-api
  prometheus:
    metrics:
      export:
        enabled: true