CREATE TABLE movies
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255)                            NOT NULL,
    duration_minutes INTEGER                                 NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    reservation_id BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE reservation_seats
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    reservation_id BIGINT                                  NOT NULL,
    screening_id   BIGINT                                  NOT NULL,
    seat_id        BIGINT                                  NOT NULL,
    price          INTEGER                                 NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_reservation_seats PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    screening_id BIGINT                                  NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    expire_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    theater_id   BIGINT                                  NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    row_count    INTEGER                                 NOT NULL,
    column_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE screening_prices
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    screening_id BIGINT                                  NOT NULL,
    seat_type    VARCHAR(255)                            NOT NULL,
    price        INTEGER                                 NOT NULL,
    CONSTRAINT pk_screening_prices PRIMARY KEY (id)
);

CREATE TABLE screenings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    movie_id   BIGINT                                  NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_screenings PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    room_id       BIGINT                                  NOT NULL,
    row_number    INTEGER,
    column_number INTEGER,
    seat_type     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE theaters
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_theaters PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255),
    status     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE reservations
    ADD CONSTRAINT uc_13f5101b834e8f1fa44d96ffc UNIQUE (id, screening_id);

ALTER TABLE rooms
    ADD CONSTRAINT uc_1c556aad22b1b7f88efbe64de UNIQUE (theater_id, name);

ALTER TABLE theaters
    ADD CONSTRAINT uc_2760d48dd1abe742dc0957af5 UNIQUE (address, name);

ALTER TABLE seats
    ADD CONSTRAINT uc_5d4b97565f6f1bbb1409ecce5 UNIQUE (room_id, row_number, column_number);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE screening_prices
    ADD CONSTRAINT uc_7c78c7488bfe54b5ce81bdcc3 UNIQUE (screening_id, seat_type);

ALTER TABLE reservation_seats
    ADD CONSTRAINT uc_88460c8d64ea8b9577089c87e UNIQUE (screening_id, seat_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_9052dfd540933abfd7cb916a9 UNIQUE (reservation_id);

ALTER TABLE screenings
    ADD CONSTRAINT uc_d82da32ccf9c464c5d3e7e1d1 UNIQUE (room_id, start_time);

CREATE INDEX idx_users_status ON users (status);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reservation_seats
    ADD CONSTRAINT FK_RESERVATION_SEATS_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE reservation_seats
    ADD CONSTRAINT FK_RESERVATION_SEATS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id);

ALTER TABLE reservation_seats
    ADD CONSTRAINT FK_RESERVATION_SEATS_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seats (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_THEATER FOREIGN KEY (theater_id) REFERENCES theaters (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE screening_prices
    ADD CONSTRAINT FK_SCREENING_PRICES_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);