CREATE TABLE movie_casts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id   BIGINT                                  NOT NULL,
    actor_name VARCHAR(255)                            NOT NULL,
    role_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_movie_casts PRIMARY KEY (id),
    CONSTRAINT fk_movie_casts_movie FOREIGN KEY (movie_id) REFERENCES movies (id),
    CONSTRAINT uk_movie_casts_movie_actor_role UNIQUE (movie_id, actor_name, role_name)
);

CREATE TABLE movie_ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    movie_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    score      INTEGER                                 NOT NULL,
    CONSTRAINT pk_movie_ratings PRIMARY KEY (id),
    CONSTRAINT fk_movie_ratings_movie FOREIGN KEY (movie_id) REFERENCES movies (id),
    CONSTRAINT fk_movie_ratings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_movie_ratings_movie_user UNIQUE (movie_id, user_id),
    CONSTRAINT chk_movie_ratings_score CHECK (score >= 1 AND score <= 5)
);

ALTER TABLE movies
    ADD director VARCHAR(255) NOT NULL DEFAULT 'Unknown';

ALTER TABLE movies
    ADD thumbnail_url VARCHAR(255);

ALTER TABLE movies
    ADD average_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00;

ALTER TABLE movies
    ADD rating_count INTEGER NOT NULL DEFAULT 0;

CREATE INDEX idx_movie_casts_movie_id
    ON movie_casts(movie_id);

CREATE INDEX idx_movie_ratings_movie_id
    ON movie_ratings(movie_id);

CREATE INDEX idx_movie_ratings_user_id
    ON movie_ratings(user_id);