CREATE TABLE movie_thumbnails
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    movie_id   BIGINT                                  NOT NULL,
    image_url  TEXT                                    NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    is_primary BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_movie_thumbnails PRIMARY KEY (id)
);

ALTER TABLE movies
    ADD genre VARCHAR(255);

ALTER TABLE movies
    ADD language VARCHAR(255);

ALTER TABLE movies
    ADD minimum_age INTEGER;

ALTER TABLE movies
    ADD release_date date;

ALTER TABLE movies
    ADD trailer_url VARCHAR(255);

ALTER TABLE movie_thumbnails
    ADD CONSTRAINT FK_MOVIE_THUMBNAILS_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

CREATE INDEX idx_movie_thumbnails_movie_id ON movie_thumbnails (movie_id);

ALTER TABLE movies
DROP
COLUMN thumbnail_url;

ALTER TABLE theater_thumbnails
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE theater_thumbnails
    ALTER COLUMN updated_at SET NOT NULL;